[workspace]
default-members = ["apollo-router"]
members = [
    "apollo-router",
    "apollo-router-benchmarks",
    "apollo-router-scaffold",
    "examples/add-timestamp-header",
    "examples/async-auth",
    "examples/cookies-to-headers",
    "examples/embedded",
    "examples/context",
    "examples/forbid-anonymous-operations",
    "examples/hello-world",
    "examples/status-code-propagation",
    "examples/op-name-to-header",
    "examples/rhai-logging",
    "examples/rhai-data-response-mutate",
    "examples/rhai-error-response-mutate",
    "examples/rhai-subgraph-request-log",
    "examples/rhai-surrogate-cache-key",
    "examples/supergraph_sdl",
    "examples/jwt-auth",
    "fuzz",
    "xtask",
]

# this makes build scripts and proc macros faster to compile
[profile.dev.build-override]
# If you un-comment the next line with 1.60.0, compile fails on circle-ci linux
# debug = false
strip = "debuginfo"
incremental = false

# If building a dhat feature, you must use this profile
# e.g. heap allocation tracing: cargo build --profile release-dhat --features dhat-heap 
# e.g. heap and ad-hoc allocation tracing: cargo build --profile release-dhat --features dhat-heap,dhat-ad-hoc
[profile.release-dhat]
inherits = "release"
debug = 1

# TODO: to delete
# [patch.crates-io]
# opentelemetry = { git = "https://github.com/open-telemetry/opentelemetry-rust.git", rev = "e5ef3552efab2bdbf2f838023c37461cd799ab2c"}
# opentelemetry-http = { git = "https://github.com/open-telemetry/opentelemetry-rust.git", rev = "e5ef3552efab2bdbf2f838023c37461cd799ab2c"}
# opentelemetry-jaeger = { git = "https://github.com/open-telemetry/opentelemetry-rust.git", rev = "e5ef3552efab2bdbf2f838023c37461cd799ab2c"}
# opentelemetry-zipkin = { git = "https://github.com/open-telemetry/opentelemetry-rust.git", rev = "e5ef3552efab2bdbf2f838023c37461cd799ab2c"}
# opentelemetry-datadog = { git = "https://github.com/open-telemetry/opentelemetry-rust.git", rev = "e5ef3552efab2bdbf2f838023c37461cd799ab2c"}