[template]
name = "apollo-router"
author = "Apollo"
version = "0.1.0"

exclude = [
    "./target"
]

disable_templating = [
    "./scaffold/**/*"
]

# Notes to display at the end of the generation
notes = """
Created new Apollo Router project '{{name}}'.

> Note: The Apollo Router is made available under the Elastic License v2.0 (ELv2).
> Read [our licensing page](https://www.apollographql.com/docs/resources/elastic-license-v2-faq/) for more details.
"""

# Parameters are basically all the variables needed to generate your template using templating.
# It will be displayed as prompt to interact with user (thanks to the message subfield).
# All the parameters will be available in your templates as variables (example: `{{description}}`).
[parameters]
# [parameters.name] is already reserved

